### ISSUE TITLE
Which default theme ?

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#463]
Oscar is the current default theme.

In my opinion, the simple themes look nicer, but it has some issues compare to the Oscar theme:
* it doesn't support RTL languages (doable with some LESS mixins).
* it doesn't follow the ARIA recommendations.
* it doesn't support the infinite scroll and some other features.

At some point, I would like to the simple theme the default one.

**Comment by mrpaulblack** [comment]
In my opinion the simple theme can be set as default when these are implemented / fixed (highly opinionated):


- [x] the dark mode  gets exposed in settings and as a toggle in the navbar (I started on that one; well or at least tried: https://github.com/MrPaulBlack/searxng/tree/dark-theme-pref-toggle)
- [x] make the preferences work on mobile (so fix for: #356 and #351 as well as https://github.com/searxng/searxng/issues/176#issuecomment-927746318)
- [x] make the detail modal display correctly on mobile (#445)
- [x] (maybe?) make the opening pages on a new tab plugin work (I was looking at: https://github.com/searxng/searxng/blob/e4025cd1644e749168d40f63cf6720e7764b6a7f/searx/templates/simple/macros.html#L16 and I have honestly no idea, why it would not work, since its a 1to1 copy from oscar)
- [x] solve CSP error with autocomplete in simple theme (the current lib adds style attributes to html; see #426 to solve #352)

(the most important thing [in my opinion] is to make the theme work as well on mobile as it does on desktop and tablet and to make it clear that it does indeed support a dark mode now; since its not clear how to switch between light and dark version rn)

**Comment by mrpaulblack** [comment]
@dalf I am not really sure how to implement the dark theme toggle and setting entry, because I am not well versed with the js files of the simple theme and the webadapter.py.... So if you want to take the dark mode toggle (and auto theme as well as pref. entry), than I would like to rework preferences to work on mobile... (Going to start work on this next week)...

**Comment by dalf** [comment]
@mrpaulblack no problem, I will do it :)

**Comment by return42** [comment]
While we are here.. I would like to insist on PR https://github.com/searxng/searxng/pull/426 which solves issue https://github.com/searxng/searxng/issues/352 .. what is a show stopper for me :-o

[EDIT] see screen shot in https://github.com/searxng/searxng/issues/352#issuecomment-930880903 .. or test simple theme on https://darmarit.org/searx/

**Comment by mrpaulblack** [comment]
Closing; Since most issues listed here are already fixed and the ones that are not are already part of https://github.com/searxng/searxng/projects/1
